services:

  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:userdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    networks:
      - microservices-net

  product-service:
    build: ./product_service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:productdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    networks:
      - microservices-net

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:cartdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      USER_SERVICE_URL: http://user-service:8081
      PRODUCT_SERVICE_URL: http://product-service:8082
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: cart-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://cart-service:8083
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/users/*/cart/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: user-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://user-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/users/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: product-service
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://product-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/products/**
    depends_on:
      - user-service
      - product-service
      - cart-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge