spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/*/cart/**

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

server:
  port: 8080